//
//  PurpleVideoFixtures.swift
//  damusTests
//
//  The Purple hosted-video API's own wire contract, copied verbatim.
//
//  Every body below is a byte-for-byte copy of a response recorded in
//  `rust/damus-api/tests/fixtures/video_routes.json` in the damus-io/api repo.
//  That fixture was generated by driving the deployed Node/express
//  implementation through supertest and recording status, content type and
//  body bytes; the Rust port's `tests/video_routes.rs` replays it against its
//  own router asserting byte equality. Decoding these same bytes here is what
//  pins the two sides of the wire to each other — a server-side change that
//  moves a field breaks a test on both sides rather than shipping a client that
//  quietly decodes nothing.
//
//  Two details are deliberate and must survive any edit:
//
//  - **The trailing `\n`.** Express writes one; the decoder has to tolerate it.
//  - **The PascalCase `tus_headers` keys.** They are the reason nothing here
//    may be decoded with `keyDecodingStrategy = .convertFromSnakeCase`.
//
//  This file holds no tests. It is shared because the same status bodies are
//  needed by the wire tests and by the `PendingVideo` state-machine tests, and
//  inlining nine of them twice guarantees drift.
//

import Foundation
@testable import damus

enum PurpleVideoFixtures {

    // MARK: - Response bodies

    /// `POST /video` 200 — the whole authorization, including the four PascalCase TUS header keys.
    ///
    /// Fixture case: *authorizing an upload returns TUS credentials and records the row*.
    static let authorize200 = "{\"video_id\":\"1bdab18a-0dc5-4ad6-9874-092ec58cd6b5\",\"library_id\":\"mock-library\",\"expiry\":1706666400,\"authorization_signature\":\"a7806312560fbbbcfd51e49a4df721dd281391bfffdd0b7267eb07c553fceb83\",\"tus_endpoint\":\"https://video.bunnycdn.com/tusupload\",\"tus_headers\":{\"AuthorizationSignature\":\"a7806312560fbbbcfd51e49a4df721dd281391bfffdd0b7267eb07c553fceb83\",\"AuthorizationExpire\":\"1706666400\",\"LibraryId\":\"mock-library\",\"VideoId\":\"1bdab18a-0dc5-4ad6-9874-092ec58cd6b5\"},\"playback_url\":\"https://mock-pull-zone.b-cdn.net/1bdab18a-0dc5-4ad6-9874-092ec58cd6b5/playlist.m3u8\",\"thumbnail_url\":\"https://mock-pull-zone.b-cdn.net/1bdab18a-0dc5-4ad6-9874-092ec58cd6b5/thumbnail.jpg\",\"upload_deadline\":1706680800,\"quota\":{\"used_stored_bytes\":500,\"limit_stored_bytes\":2000,\"remaining_stored_bytes\":1500,\"window_seconds\":2592000}}\n"

    /// `GET` mid-encode: progress reported, nothing publishable yet.
    ///
    /// Fixture case: *polling a mid-encode video reconciles the row and reports progress*.
    static let statusEncoding = "{\"video_id\":\"37e755d0-1be3-49bc-b159-9fd1b8ec860a\",\"status\":\"encoding\",\"publishable\":false,\"terminal\":false,\"encode_progress\":45,\"encode_clean\":null,\"available_resolutions\":[\"360p\",\"480p\"],\"width\":null,\"height\":null,\"duration_seconds\":null,\"stored_bytes\":null,\"charged_stored_bytes\":500,\"issues\":[],\"playback_url\":\"https://mock-pull-zone.b-cdn.net/37e755d0-1be3-49bc-b159-9fd1b8ec860a/playlist.m3u8\",\"thumbnail_url\":\"https://mock-pull-zone.b-cdn.net/37e755d0-1be3-49bc-b159-9fd1b8ec860a/thumbnail.jpg\",\"title\":\"Damus Purple video\",\"created_at\":1706659200,\"updated_at\":1706659200,\"upload_deadline\":1706680800,\"stale\":false}\n"

    /// `GET` after a clean encode: publishable, upright at 1080x1920, size settled.
    ///
    /// Fixture case: *a finished clean encode is publishable, upright, and settles its size*.
    static let statusReadyClean = "{\"video_id\":\"29d51095-efff-4952-8e81-d1a546a78351\",\"status\":\"ready\",\"publishable\":true,\"terminal\":true,\"encode_progress\":100,\"encode_clean\":true,\"available_resolutions\":[\"360p\",\"480p\",\"720p\"],\"width\":1080,\"height\":1920,\"duration_seconds\":93,\"stored_bytes\":700,\"charged_stored_bytes\":700,\"issues\":[{\"code\":4,\"level\":1,\"severity\":\"info\",\"message\":\"The source has a variable frame rate. This is normal for phone recordings and does not affect playback.\"}],\"playback_url\":\"https://mock-pull-zone.b-cdn.net/29d51095-efff-4952-8e81-d1a546a78351/playlist.m3u8\",\"thumbnail_url\":\"https://mock-pull-zone.b-cdn.net/29d51095-efff-4952-8e81-d1a546a78351/thumbnail.jpg\",\"title\":\"Damus Purple video\",\"created_at\":1706659200,\"updated_at\":1706659200,\"upload_deadline\":1706680800,\"stale\":false}\n"

    /// `GET` after a damaged encode: a full rendition ladder, `publishable: false`.
    ///
    /// Fixture case: *a damaged encode reaches status 4 and is reported as damaged, not ready*.
    static let statusDamaged = "{\"video_id\":\"41832318-ea59-4933-8ed5-bc7d281de31a\",\"status\":\"damaged\",\"publishable\":false,\"terminal\":true,\"encode_progress\":100,\"encode_clean\":false,\"available_resolutions\":[\"360p\",\"480p\",\"720p\"],\"width\":1080,\"height\":1920,\"duration_seconds\":null,\"stored_bytes\":700,\"charged_stored_bytes\":700,\"issues\":[{\"code\":4,\"level\":1,\"severity\":\"info\",\"message\":\"The source has a variable frame rate. This is normal for phone recordings and does not affect playback.\"},{\"code\":2,\"level\":2,\"severity\":\"damaged\",\"message\":\"Part of this video could not be transcoded, so the result may be incomplete.\"}],\"playback_url\":\"https://mock-pull-zone.b-cdn.net/41832318-ea59-4933-8ed5-bc7d281de31a/playlist.m3u8\",\"thumbnail_url\":\"https://mock-pull-zone.b-cdn.net/41832318-ea59-4933-8ed5-bc7d281de31a/thumbnail.jpg\",\"title\":\"Damus Purple video\",\"created_at\":1706659200,\"updated_at\":1706659200,\"upload_deadline\":1706680800,\"stale\":false}\n"

    /// `GET` after a failed encode: terminal, and frozen at 5% progress.
    ///
    /// Fixture case: *a failed encode is terminal at 5% progress and leaks nothing from the provider*.
    static let statusFailed = "{\"video_id\":\"5fc049f9-dff9-4355-a3da-11581592d153\",\"status\":\"failed\",\"publishable\":false,\"terminal\":true,\"encode_progress\":5,\"encode_clean\":false,\"available_resolutions\":[],\"width\":null,\"height\":null,\"duration_seconds\":null,\"stored_bytes\":0,\"charged_stored_bytes\":0,\"issues\":[{\"code\":7,\"level\":3,\"severity\":\"fatal\",\"message\":\"The uploaded file could not be read as a video.\"}],\"playback_url\":\"https://mock-pull-zone.b-cdn.net/5fc049f9-dff9-4355-a3da-11581592d153/playlist.m3u8\",\"thumbnail_url\":\"https://mock-pull-zone.b-cdn.net/5fc049f9-dff9-4355-a3da-11581592d153/thumbnail.jpg\",\"title\":\"Damus Purple video\",\"created_at\":1706659200,\"updated_at\":1706659200,\"upload_deadline\":1706680800,\"stale\":false}\n"

    /// `GET` where every issue code is unknown, plus one with `"code": null`.
    ///
    /// Fixture case: *an issue code we have never seen falls back to generic copy*.
    static let statusUnknownIssueCodes = "{\"video_id\":\"3fcf631b-1e3b-4950-8d28-c44788074dba\",\"status\":\"damaged\",\"publishable\":false,\"terminal\":true,\"encode_progress\":100,\"encode_clean\":false,\"available_resolutions\":[\"360p\",\"480p\",\"720p\"],\"width\":1080,\"height\":1920,\"duration_seconds\":null,\"stored_bytes\":700,\"charged_stored_bytes\":700,\"issues\":[{\"code\":99,\"level\":1,\"severity\":\"info\",\"message\":\"The video service reported a note about this upload.\"},{\"code\":98,\"level\":2,\"severity\":\"damaged\",\"message\":\"The video service reported a problem while transcoding this upload.\"},{\"code\":97,\"level\":3,\"severity\":\"fatal\",\"message\":\"The video service could not process this upload.\"},{\"code\":null,\"level\":2,\"severity\":\"damaged\",\"message\":\"The video service reported a problem while transcoding this upload.\"},{\"code\":4,\"level\":0,\"severity\":\"info\",\"message\":\"The source has a variable frame rate. This is normal for phone recordings and does not affect playback.\"}],\"playback_url\":\"https://mock-pull-zone.b-cdn.net/3fcf631b-1e3b-4950-8d28-c44788074dba/playlist.m3u8\",\"thumbnail_url\":\"https://mock-pull-zone.b-cdn.net/3fcf631b-1e3b-4950-8d28-c44788074dba/thumbnail.jpg\",\"title\":\"Damus Purple video\",\"created_at\":1706659200,\"updated_at\":1706659200,\"upload_deadline\":1706680800,\"stale\":false}\n"

    /// `GET` before any bytes arrive.
    ///
    /// Fixture case: *polling is cached, and a settled video stops reaching the provider entirely*.
    static let statusAuthorized = "{\"video_id\":\"15ffb418-79a4-48c0-bff2-d2d313f88e73\",\"status\":\"authorized\",\"publishable\":false,\"terminal\":false,\"encode_progress\":0,\"encode_clean\":null,\"available_resolutions\":[],\"width\":null,\"height\":null,\"duration_seconds\":null,\"stored_bytes\":null,\"charged_stored_bytes\":500,\"issues\":[],\"playback_url\":\"https://mock-pull-zone.b-cdn.net/15ffb418-79a4-48c0-bff2-d2d313f88e73/playlist.m3u8\",\"thumbnail_url\":\"https://mock-pull-zone.b-cdn.net/15ffb418-79a4-48c0-bff2-d2d313f88e73/thumbnail.jpg\",\"title\":\"Damus Purple video\",\"created_at\":1706659200,\"updated_at\":1706659200,\"upload_deadline\":1706680800,\"stale\":false}\n"

    /// `GET` on a finished encode whose stored size has not landed: `stored_bytes` null, reservation still charged.
    ///
    /// Fixture case: *a finished encode with no size yet keeps its reservation and is retried*.
    static let statusReadyNoSizeYet = "{\"video_id\":\"52a648f0-3d7e-4d5f-843c-99a086d75a9d\",\"status\":\"ready\",\"publishable\":true,\"terminal\":true,\"encode_progress\":100,\"encode_clean\":true,\"available_resolutions\":[\"360p\",\"480p\",\"720p\"],\"width\":1080,\"height\":1920,\"duration_seconds\":93,\"stored_bytes\":null,\"charged_stored_bytes\":500,\"issues\":[{\"code\":4,\"level\":1,\"severity\":\"info\",\"message\":\"The source has a variable frame rate. This is normal for phone recordings and does not affect playback.\"}],\"playback_url\":\"https://mock-pull-zone.b-cdn.net/52a648f0-3d7e-4d5f-843c-99a086d75a9d/playlist.m3u8\",\"thumbnail_url\":\"https://mock-pull-zone.b-cdn.net/52a648f0-3d7e-4d5f-843c-99a086d75a9d/thumbnail.jpg\",\"title\":\"Damus Purple video\",\"created_at\":1706659200,\"updated_at\":1706659200,\"upload_deadline\":1706680800,\"stale\":false}\n"

    /// `GET` the server could not refresh from the provider. The stored row answers, marked stale. Not an error.
    ///
    /// Fixture case: *a provider failure is not fatal -- the stored row answers, marked stale*.
    static let statusStale = "{\"video_id\":\"a99119aa-5d05-4b8b-9616-aa9502eb2fc6\",\"status\":\"encoding\",\"publishable\":false,\"terminal\":false,\"encode_progress\":45,\"encode_clean\":null,\"available_resolutions\":[],\"width\":null,\"height\":null,\"duration_seconds\":null,\"stored_bytes\":null,\"charged_stored_bytes\":500,\"issues\":[],\"playback_url\":\"https://mock-pull-zone.b-cdn.net/a99119aa-5d05-4b8b-9616-aa9502eb2fc6/playlist.m3u8\",\"thumbnail_url\":\"https://mock-pull-zone.b-cdn.net/a99119aa-5d05-4b8b-9616-aa9502eb2fc6/thumbnail.jpg\",\"title\":\"Damus Purple video\",\"created_at\":1706659200,\"updated_at\":1706659200,\"upload_deadline\":1706680800,\"stale\":true}\n"

    /// `GET` on a reservation whose upload never arrived, past its deadline.
    ///
    /// Fixture case: *an upload that never arrived is expired once its deadline passes*.
    static let statusExpired = "{\"video_id\":\"f847603d-1415-4650-98f8-17135a89230d\",\"status\":\"expired\",\"publishable\":false,\"terminal\":true,\"encode_progress\":0,\"encode_clean\":null,\"available_resolutions\":[],\"width\":null,\"height\":null,\"duration_seconds\":null,\"stored_bytes\":null,\"charged_stored_bytes\":0,\"issues\":[],\"playback_url\":\"https://mock-pull-zone.b-cdn.net/f847603d-1415-4650-98f8-17135a89230d/playlist.m3u8\",\"thumbnail_url\":\"https://mock-pull-zone.b-cdn.net/f847603d-1415-4650-98f8-17135a89230d/thumbnail.jpg\",\"title\":\"Damus Purple video\",\"created_at\":1706659200,\"updated_at\":1706680800,\"upload_deadline\":1706680800,\"stale\":false}\n"

    /// `DELETE` 200 on a video that existed.
    ///
    /// Fixture case: *deleting a video removes it at the provider and tombstones the row*.
    static let deleteFresh = "{\"video_id\":\"4fc2d3b2-fa74-42df-8fce-9f107a7c28ba\",\"status\":\"deleted\",\"deleted\":true,\"already_deleted\":false,\"deleted_at\":1706659200,\"charged_stored_bytes\":700,\"quota\":{\"used_stored_bytes\":700,\"limit_stored_bytes\":2000,\"remaining_stored_bytes\":1300,\"window_seconds\":2592000}}\n"

    /// `DELETE` 200 again on the same video: idempotent, `already_deleted: true`.
    ///
    /// Fixture case: *deleting a video removes it at the provider and tombstones the row*.
    static let deleteAlreadyDeleted = "{\"video_id\":\"4fc2d3b2-fa74-42df-8fce-9f107a7c28ba\",\"status\":\"deleted\",\"deleted\":true,\"already_deleted\":true,\"deleted_at\":1706659200,\"charged_stored_bytes\":700,\"quota\":{\"used_stored_bytes\":700,\"limit_stored_bytes\":2000,\"remaining_stored_bytes\":1300,\"window_seconds\":2592000}}\n"

    /// `DELETE` 200 on an authorization whose bytes never arrived: the reservation is released, `charged_stored_bytes` 0.
    ///
    /// Fixture case: *cancelling an upload that never arrived releases its reservation*.
    static let deleteNeverUploaded = "{\"video_id\":\"d3935f3d-7915-4bac-8666-0662b3bfae5b\",\"status\":\"deleted\",\"deleted\":true,\"already_deleted\":false,\"deleted_at\":1706659200,\"charged_stored_bytes\":0,\"quota\":{\"used_stored_bytes\":0,\"limit_stored_bytes\":2000,\"remaining_stored_bytes\":2000,\"window_seconds\":2592000}}\n"

    /// 403 — no Purple account.
    ///
    /// Fixture case: *a pubkey with no Purple account cannot authorize an upload*.
    static let refusalSubscriptionMissing = "{\"error\":\"Account not found\",\"code\":\"subscription_required\"}\n"

    /// 403 — a lapsed subscriber. Same `code` as `refusalSubscriptionMissing`; only the prose differs.
    ///
    /// Fixture case: *an expired subscriber gets 403*.
    static let refusalSubscriptionExpired = "{\"error\":\"Account expired\",\"code\":\"subscription_required\"}\n"

    /// 401 — from the NIP-98 middleware, so there is no `code` field at all.
    ///
    /// Fixture case: *an unauthenticated request never reaches the subscription check*.
    static let refusalUnauthenticated = "{\"error\":\"Nostr authorization header missing\"}\n"

    /// 400 — a declared size the server will not read.
    ///
    /// Fixture case: *a malformed declared size is refused before anything is created*.
    static let refusalInvalidDeclaredBytes = "{\"error\":\"Declared upload size must be a positive whole number of bytes\",\"code\":\"invalid_declared_bytes\"}\n"

    /// 400 — a declared duration the server will not read.
    ///
    /// Fixture case: *a video past a per-video limit is declined with a code the app can render*.
    static let refusalInvalidDuration = "{\"error\":\"Declared duration must be a positive number of seconds\",\"code\":\"invalid_duration\"}\n"

    /// 400 — a title that is not a string.
    ///
    /// Fixture case: *a title is optional, sanitized, and never blank*.
    static let refusalInvalidTitle = "{\"error\":\"Title must be a string\",\"code\":\"invalid_title\"}\n"

    /// 422 — past the per-video byte limit. The limit appears only inside the English prose.
    ///
    /// Fixture case: *a video past a per-video limit is declined with a code the app can render*.
    static let refusalVideoTooLarge = "{\"error\":\"Video is larger than the 1000 byte per-video limit\",\"code\":\"video_too_large\",\"quota\":{\"used_stored_bytes\":0,\"limit_stored_bytes\":2000,\"remaining_stored_bytes\":2000,\"window_seconds\":2592000}}\n"

    /// 422 — past the per-video duration limit.
    ///
    /// Fixture case: *a video past a per-video limit is declined with a code the app can render*.
    static let refusalVideoTooLong = "{\"error\":\"Video is longer than the 600 second per-video limit\",\"code\":\"video_too_long\",\"quota\":{\"used_stored_bytes\":0,\"limit_stored_bytes\":2000,\"remaining_stored_bytes\":2000,\"window_seconds\":2592000}}\n"

    /// 402 — the rolling monthly allowance is spent.
    ///
    /// Fixture case: *the rolling monthly allowance is enforced, and is per subscriber*.
    static let refusalMonthlyQuota = "{\"error\":\"Video would exceed your monthly hosted-video allowance\",\"code\":\"monthly_quota_exceeded\",\"quota\":{\"used_stored_bytes\":2000,\"limit_stored_bytes\":2000,\"remaining_stored_bytes\":0,\"window_seconds\":2592000}}\n"

    /// 429 — three authorizations already waiting for their bytes.
    ///
    /// Fixture case: *too many uploads waiting for bytes is refused*.
    static let refusalTooManyPending = "{\"error\":\"You already have 3 uploads waiting to finish. Finish or abandon one before starting another.\",\"code\":\"too_many_pending_uploads\",\"pending_uploads\":3,\"max_pending_uploads\":3}\n"

    /// 502 — the server could not reach the video provider.
    ///
    /// Fixture case: *a provider failure leaves no row and no credentials behind*.
    static let refusalProviderUnreachable = "{\"error\":\"Could not reach the video service. Please try again.\",\"code\":\"video_provider_error\"}\n"

    /// 500 — the video object was created but could not be recorded, so it was deleted again.
    ///
    /// Fixture case: *a video object we cannot record is deleted rather than orphaned*.
    static let refusalVideoRowFailed = "{\"error\":\"Could not record the upload. Please try again.\",\"code\":\"video_row_failed\"}\n"

    /// 404 — someone else's video is indistinguishable from one that does not exist.
    ///
    /// Fixture case: *someone else's video is indistinguishable from one that does not exist*.
    static let refusalVideoNotFound = "{\"error\":\"No such video\",\"code\":\"video_not_found\"}\n"

    /// 410 — the row is a tombstone.
    ///
    /// Fixture case: *deleting a video removes it at the provider and tombstones the row*.
    static let refusalVideoDeleted = "{\"error\":\"This video was deleted\",\"code\":\"video_deleted\",\"video_id\":\"4fc2d3b2-fa74-42df-8fce-9f107a7c28ba\",\"deleted_at\":1706659200}\n"

    /// 400 `text/html` — a request body that is valid JSON but not an object, rejected by body-parser before any handler runs.
    ///
    /// Fixture case: *a body that is not json at all*.
    static let htmlBadRequest = "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Bad Request</pre>\n</body>\n</html>\n"

    /// 500 `text/html` — a nonsensical route knob, which the deployed express app re-reads from the environment on every request.
    ///
    /// Fixture case: *a nonsensical route knob is a per-request failure*.
    static let htmlInternalServerError = "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Internal Server Error</pre>\n</body>\n</html>\n"

    /// 503 — hosted video is not configured on this deployment.
    ///
    /// Not in the JSON fixture: the express route tests reach it by nulling the
    /// client after registration, which no recorded request can do. Transcribed
    /// from `rust/damus-api/src/routes/video.rs`'s
    /// `an_unconfigured_provider_is_a_503`, which asserts these exact bytes.
    static let refusalVideoUnavailable = "{\"error\":\"Hosted video is not configured on this server\",\"code\":\"video_unavailable\"}\n"

    /// 500 — a failure the Node implementation cannot have, since its store is
    /// LMDB and a read on a live environment does not fail. The Rust port's
    /// Postgres can be down, so it answers this. Never seen against today's
    /// deployment; here because the client has to map it.
    ///
    /// Transcribed from `Refusal::internal` in `routes/video.rs`.
    static let refusalInternalError = "{\"error\":\"Internal server error\",\"code\":\"internal_error\"}\n"

    // MARK: - Deliberate garbage
    //
    // Not from the API. These exist so the tests can prove that a body nothing
    // on the wire would ever produce still leaves as a `PurpleVideoAPIError`.

    /// A success body cut off mid-object.
    static let truncatedJSON = "{\"video_id\":\"1bdab18a-0dc5-4ad6-9874-09"

    /// Valid JSON, wrong shape entirely.
    static let jsonOfTheWrongShape = "[1,2,3]\n"

    /// A body that is not text at all.
    static let binaryGarbage = Data([0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10, 0x4A, 0x46])

    // MARK: - Building responses

    /// An `application/json` response, as express sends one.
    static func json(_ status: Int, _ body: String) -> PurpleVideoHTTPResponse {
        PurpleVideoHTTPResponse(
            status: status,
            headers: ["Content-Type": "application/json; charset=utf-8"],
            body: Data(body.utf8)
        )
    }

    /// A `text/html` response. Express answers three of the recorded cases this
    /// way, so this is not a hypothetical.
    static func html(_ status: Int, _ body: String) -> PurpleVideoHTTPResponse {
        PurpleVideoHTTPResponse(
            status: status,
            headers: ["Content-Type": "text/html; charset=utf-8"],
            body: Data(body.utf8)
        )
    }

    /// A response with no `Content-Type` at all.
    static func untyped(_ status: Int, _ body: Data) -> PurpleVideoHTTPResponse {
        PurpleVideoHTTPResponse(status: status, body: body)
    }

    // MARK: - Decoded shortcuts

    /// A decoded status, for tests that are about what happens *after* decoding.
    static func status(_ body: String) throws -> PurpleVideoStatus {
        try PurpleVideoWire.status(json(200, body))
    }

    /// A decoded authorization, for the same reason.
    static func authorization(_ body: String = authorize200) throws -> PurpleVideoAuthorization {
        try PurpleVideoWire.authorization(json(200, body))
    }
}
