#ifndef META_READER_H
#define META_READER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct NdbEventMeta_table *NdbEventMeta_table_t;
typedef struct NdbEventMeta_table *NdbEventMeta_mutable_table_t;
typedef const flatbuffers_uoffset_t *NdbEventMeta_vec_t;
typedef flatbuffers_uoffset_t *NdbEventMeta_mutable_vec_t;
#ifndef NdbEventMeta_file_identifier
#define NdbEventMeta_file_identifier 0
#endif
/* deprecated, use NdbEventMeta_file_identifier */
#ifndef NdbEventMeta_identifier
#define NdbEventMeta_identifier 0
#endif
#define NdbEventMeta_type_hash ((flatbuffers_thash_t)0xa8c23be8)
#define NdbEventMeta_type_identifier "\xe8\x3b\xc2\xa8"
#ifndef NdbEventMeta_file_extension
#define NdbEventMeta_file_extension "bin"
#endif



struct NdbEventMeta_table { uint8_t unused__; };

static inline size_t NdbEventMeta_vec_len(NdbEventMeta_vec_t vec)
__flatbuffers_vec_len(vec)
static inline NdbEventMeta_table_t NdbEventMeta_vec_at(NdbEventMeta_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(NdbEventMeta_table_t, vec, i, 0)
__flatbuffers_table_as_root(NdbEventMeta)

__flatbuffers_define_scalar_field(0, NdbEventMeta, received_at, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_scalar_field(1, NdbEventMeta, reactions, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_scalar_field(2, NdbEventMeta, quotes, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_scalar_field(3, NdbEventMeta, reposts, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_scalar_field(4, NdbEventMeta, zaps, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_scalar_field(5, NdbEventMeta, zap_total, flatbuffers_int64, int64_t, INT64_C(0))


#include "flatcc_epilogue.h"
#endif /* META_READER_H */
