#ifndef META_VERIFIER_H
#define META_VERIFIER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef META_READER_H
#include "meta_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int NdbEventMeta_verify_table(flatcc_table_verifier_descriptor_t *td);

static int NdbEventMeta_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* received_at */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* reactions */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* quotes */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 4, 4) /* reposts */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 4, 4) /* zaps */)) return ret;
    if ((ret = flatcc_verify_field(td, 5, 8, 8) /* zap_total */)) return ret;
    return flatcc_verify_ok;
}

static inline int NdbEventMeta_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, NdbEventMeta_identifier, &NdbEventMeta_verify_table);
}

static inline int NdbEventMeta_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, NdbEventMeta_type_identifier, &NdbEventMeta_verify_table);
}

static inline int NdbEventMeta_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &NdbEventMeta_verify_table);
}

static inline int NdbEventMeta_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &NdbEventMeta_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* META_VERIFIER_H */
