name: Test
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"
jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Running Tests
      run: xcodebuild test -scheme damus -project damus.xcodeproj -destination 'platform=iOS Simulator,name=Any iOS Device,OS=16.2' | xcpretty && exit ${PIPESTATUS[0]}