name: Test
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"
jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: BlueIntent/iOS-helper-action@v0.0.1
        with:
          action: 'test'